// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeP26M35w47iwdrHQ9a_0zmTTyEMpVKNk',
    appId: '1:244913636625:web:30562f5b816a345fca78b0',
    messagingSenderId: '244913636625',
    projectId: 'imtiaz-e2ddc',
    authDomain: 'imtiaz-e2ddc.firebaseapp.com',
    storageBucket: 'imtiaz-e2ddc.firebasestorage.app',
    measurementId: 'G-9CXTBSCDBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGBLU8-1PbX2Mhx6EXkqztA-SMHKTCTRM',
    appId: '1:244913636625:android:3a1511617f2f8734ca78b0',
    messagingSenderId: '244913636625',
    projectId: 'imtiaz-e2ddc',
    storageBucket: 'imtiaz-e2ddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT9nbSRqRDYWaxoJnk4wjexla43gxAA8U',
    appId: '1:244913636625:ios:d0ab1dc68afa699fca78b0',
    messagingSenderId: '244913636625',
    projectId: 'imtiaz-e2ddc',
    storageBucket: 'imtiaz-e2ddc.firebasestorage.app',
    iosBundleId: 'com.example.imtiaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT9nbSRqRDYWaxoJnk4wjexla43gxAA8U',
    appId: '1:244913636625:ios:d0ab1dc68afa699fca78b0',
    messagingSenderId: '244913636625',
    projectId: 'imtiaz-e2ddc',
    storageBucket: 'imtiaz-e2ddc.firebasestorage.app',
    iosBundleId: 'com.example.imtiaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeP26M35w47iwdrHQ9a_0zmTTyEMpVKNk',
    appId: '1:244913636625:web:73fc47dddad6421dca78b0',
    messagingSenderId: '244913636625',
    projectId: 'imtiaz-e2ddc',
    authDomain: 'imtiaz-e2ddc.firebaseapp.com',
    storageBucket: 'imtiaz-e2ddc.firebasestorage.app',
    measurementId: 'G-V012HEDSMV',
  );
}
